### ISSUE TITLE
Gravitational light bending in the documentation

### ISSUE THREAD

**Issue by dfarnocchia** [IAU-ADES/ADES-Master#12]
Discussing with occultation observers, it has come out the issue of gravitational light bending.
This effect can affect astrometric positions since this relativistic effect is different between reference stars and observed small body.
Given that this effect depends on the position of the observed target, this should be modeled as part of the orbit determination process.
Therefore, observers should NOT correct the measured astrometric position to account for this effect. Rather they should report what they actually observed.

We should probably clarify this in the ADES documentation, and probably also on the MPC website somewhere.

**Comment by Bill-Gray** [comment]
Just to make sure I'm understanding you : you're saying they should report "I saw an occultation at thus-and-such time at location (RA, dec)",  where (RA, dec) is the astrometric position of the star?  (With that position usually computed by taking Gaia position,  proper motion,  and parallax and figuring out where the star was at that moment.)  That way,  we basically can treat it as if a super-precise optical observation was made of the object at those coordinates.

**Comment by dfarnocchia** [comment]
Yes, that's the correct interpretation. The format actually allows users to specify an offset, though Dave Herald et al. are now using an approach where they report a satellite style observation (i.e., with observer location specified relative to the geocenter) where the observer is a synthetic one located where the observed offset is zero.

I opened this issue because in some cases observers have been tempted to say: "Here's where I see the object, but that is not the real position because there is a differential light bending between asteroid and star. Let me correct for that so that my astrometry is more accurate."
We need to make sure that observers don't do that. This differential effect is a function of the position of the object, which is a product of the orbit determination process, not directly derived from the observations.
As such, it's on us doing orbit determination to compute that effect and include it when computing residuals, just like we do when we account for aberration (the observed position corresponds to where the object was one light time ago).

This effect applies to all optical observations that are measured relative to background stars (which is not the case for Gaia). However, it really matters only for the most accurate observations such as occultations.
And not always, e.g., when observing at the opposition light doesn't come close to the Sun. When observing at low solar elongation when the star and the asteroid are on different sides of the Sun, then this effect is more significant.

A final comment about Gaia. DR2 solar system astrometry was corrected as if the object were at infinity.
So, for orbit determination purposes you can treat these observations just like other astrometry. Remove light bending at infinity (= that of a star), which is what was applied to the data, and apply the one using the physical location of the body.
For DR3, no correction should have been applied, so the orbit determination process needs to model the (this time non-differential) light bending.
Hope this makes sense.

**Comment by Bill-Gray** [comment]
Excellent.  That all makes perfect sense to me.  _Except_ for that last paragraph;  I don't see why our friends working on Gaia-DR3 made their astrometry subtly different from every previous bit of astrometric data the world has ever seen,  including DR2.  Does this mean we need to extend ADES to specify untweaked versus tweaked astrometry?  Which currently would mean "is it DR3" vs. "is it anything else".  It just seems to be an unnecessary complication.

I suppose the other solution would be to read in the Gaia astrometry in its .CSV format and tweak it back into the "proper" system before writing it out to ADES.  I,  at least,  would prefer that solution,  though it'll really complicate my [Gaia .CSV to ADES program](https://github.com/Bill-Gray/lunar/blob/master/csv2ades.c);  it will need to know,  for each astrometric measurement,  how far away the object was at the time.  It won't be just a format converting program anymore.

**Comment by dfarnocchia** [comment]
I would argue that both DR2 and DR3 are different from traditional astrometry.
Polo Tanga tried to explain it to me, though I can't remember the details. The bottom line is that they are not measuring relative to background stars but the measurement is directly tied to the inertial frame.

DR2 was strange to me because they applied the gravitational light bending correction as if the object was at infinity. They are not doing that for DR3, which I think is fine.
I don't think their data need to be preprocessed in any way, the fitting program just needs to be smart and process the Gaia-DR3 observables in a slightly different way.

**Comment by stevechesley** [comment]
This was added as a best practice to the ADES Description PDF a few months ago: 

> ...observers should not make any corrections for relativistic path curvature of photons (“lensing” or “light bending”) as this is position dependent and therefore must be applied when fitting an orbit to the astrometry.

@federicaspoto, the point could also be mentioned on the MPC website and/or a monthly newsletter. But closing this issue as it is not about a problem with ADES.
