### ISSUE TITLE
ADES Description

### ISSUE THREAD

**Issue by federicaspoto** [IAU-ADES/ADES-Master#19]
@stevechesley ,
The new name of the ADES_Description.pdf file actually breaks our website (a few hyperlinks). 
The page is https://www.minorplanetcenter.net/iau/info/ADES.html and the broken hyperlinks are in the first section "Astrometry Data Exchange Standard". 

Is that okay if we keep the usual name for the main current version and if you want we can keep track of the other versions in a different folder?

**Comment by stevechesley** [comment]
Fixed and pushed.
