### ISSUE TITLE
Change request - magnitudes

### ISSUE THREAD

**Issue by joemasiero** [IAU-ADES/ADES-Master#2]
I'm looking over the current implementation of ADES, and I noticed an item that could possibly be improved regarding the way magnitudes are reported.

Currently, as far as I understand, each `<optical>` block contains a `<mag>` and a `<band>`.  However, if an observatory is able to take simultaneous photometry at two or more wavelengths (e.g. WISE, NEOCam), there is no way to report this currently.  I would be forced to choose one band or the other, or submit multiple <optical> blocks at the same time/position.

If it's not too late to change this, I would suggest moving the band into the text description of `<mag>` and `<rmsMag>`, so submissions would look like:

`<mag band="NC1">13.0</mag>`
`<rmsMag band="NC1">0.1</mag>`

This would allow for multiple magnitude submissions in each optical block, and the band would be held as an .attrib while the value would be held as .text

Joe

**Comment by stevechesley** [comment]
Joe, thanks for the suggestion. However, at this point in time, ADES version 2017 is frozen to facilitate transition and widespread adoption. This particular issue was discussed at some point and it was judged best to save it for the next revision, or until there are actually photometric data of this form available. (Are there simultaneous WISE photometric measurements on hand? And would the project resubmit detections with all of the photometry?) Using an attribute could be a good approach in XML, but there is the ADES requirement for lossless transformation between the PSV and XML formats. Anyway, we'll keep this request open and revisit when moving to the subsequent version.

**Comment by joemasiero** [comment]
OK, thanks for letting me know Steve.  WISE does have such data, though we hadn't planned on submitting it into MPC as the old format didn't take it and all the photometry is now being served by IRSA, but there was interest in this option for NEOCam as a way of releasing the photometry to the community faster.  If the MPC so desired, it would be possible for the reprocessed WISE cryo data to be submitted with 4 band photometry, but that is not the baseline plan (though since I'm going to have to regenerate the astrometry from 80-col to XML, it's a trivial increase in work effort to add the magnitudes).

**Comment by stevechesley** [comment]
Given that NEO Surveyor no longer intends to submit photometry in multiple passbands, it seems that this functionality is no longer needed in the near term. The issue can be reopened if the need arises in the future.
