### ISSUE TITLE
New Packed Formats

### ISSUE THREAD

**Issue by matthewjohnpayne** [IAU-ADES/ADES-Master#31]
It would be good to accommodate the new packed designation schemes for both the permIDs and the provIDs. 
 - The code to pack (and unpack) the permIDs (starting with a tilde) seems to exist in packUtil.py but is commented-out
 - The code to pack (and unpack) the provIDs doesn't seem to exist at all. 

N.B. These get used within the xmltompc80col.py & mpc80coltoxml.py codes 

Further, I'm wondering whether we could add an _option_ to silently continue (and not error-out) in some circumstances.

**Comment by stevechesley** [comment]
Agreed. Will look to update `xmltompc80col.py` and `mpc80coltoxml.py` in the near future.

**Comment by stevenstetzler** [comment]
I opened #34 for this. As far as I can tell, permIDs starting with `~` are matched and handled via `packUtil.minorplanetPackedIDRegex` and `packUtil.unpackPackedID` and `packUtil.packTupleID`. The code I found commented out:
```
#minorplanetPackedPermIDRegex = re.compile('^([0-9A-Za-z])(\d{4})$')
...
#minorplanetPackedProvIDRegex = re.compile('^ ([I-K])(\d{2})([A-HJ-Y])([a-zA-Z0-9])(\d)([A-HJ-Z])$')
```
isn't used elsewhere.

Packing and unpacking of provIDs seems to be handled already except for using the extended packed format, which I've implemented in the PR.
