### ISSUE TITLE
Add checks on magnitude values. 

### ISSUE THREAD

**Issue by federicaspoto** [IAU-ADES/ADES-Master#35]
@stevechesley we noticed that people can submit wrong values of magnitudes and they would pass the ADES validation. An example was a submission with a magnitude value of 209 instead of 20.9. Can we add a check on the magnitude as we do for RA or Dec? 

(cc @matthewjohnpayne )

**Comment by stevechesley** [comment]
This was discussed sometime in the distant past, but it seemed hard to put strict bounds on this, taking into account the possibility of close approaches by large asteroids (potentially from a spacecraft), and major efforts to detect extremely faint objects.

A very large asteroid (H=12 mag) at the lunar distance could be V=-1 mag. And I seem to recall that there have been observations reported in the range 27-28mag. What limits would you propose? It seems like -5 mag to +35 mag  should be safe for a very long time.

**Comment by stevechesley** [comment]
Resolved with PR #37
