### ISSUE TITLE
Allow ADES submissions without the 'observer' field. 

### ISSUE THREAD

**Issue by federicaspoto** [IAU-ADES/ADES-Master#38]
@stevechesley we would like to allow ADES submissions **without the 'observer' field**. This is already possible when people submit observations in obs80-column format. The issue was raised on a Jira ticket: the submitters could not find any information on who was the observer, nor the PI of the program who took the observations (archival images of VST and DECam). 

It would be possible to create a 'fake' general observer name, but we (MPC) prefer not to do that and change ADES. What do you think? 

Thanks!
Federica

**Comment by stevechesley** [comment]
Resolved with PR #37.
