### ISSUE TITLE
Converting xml to obs80 -- roving observer coordinates

### ISSUE THREAD

**Issue by margaret-pan** [IAU-ADES/ADES-Master#39]
I was using xmltompc80col.py to convert ADES xml to what becomes 2-line observations in the 80-col format, and it looks like there's an issue when the xml has observatory coordinates with extra precision. It seems these are not truncated during the conversion to 80-col, so that for example

`      <optical>`
`        <trkSub>MYDESIG</trkSub>`
`        <mode>CMO</mode>`
`        <stn>246</stn>`
`        <sys>ICRF_AU</sys>`
`        <ctr>10</ctr>`
`        <pos1>-0.6341405090</pos1>`
`        <pos2>0.6812469710</pos2>`
`        <pos3>0.2952090970</pos3>`
`        <obsTime>2024-01-31T12:48:41.616Z</obsTime>`
`        <ra>21.63341</ra>`
`        <dec>-30.11656</dec>`
`        <rmsRA>0.6361</rmsRA>`
`        <rmsDec>0.5936</rmsDec>`
`        <rmsCorr>-0.0836</rmsCorr>`
`        <astCat>Gaia3</astCat>`
`        <remarks>this is a test</remarks>`
`      </optical>`

becomes

`     MYDESIG  S2024 01 31.53381501 26 32.018-30 06 59.62               W     246`
`     MYDESIG  s2024 01 31.5338152 -0.6341405090 +0.6812469710 +0.2952090970        246`

with an extra long 2nd line.

I've attached a sample xml with the above, and the obs80 output from xmltompc80col.py (Github forced me to add .txt as extension).

[testxml.obs.txt](https://github.com/IAU-ADES/ADES-Master/files/13994638/testxml.obs.txt)
[test.xml.txt](https://github.com/IAU-ADES/ADES-Master/files/13994639/test.xml.txt)

**Comment by stevechesley** [comment]
This should be fixed. See notes on PR #40.

**Comment by margaret-pan** [comment]
Thanks for the clarification and the change!
