### ISSUE TITLE
Change request: Add filter to Photometry Group

### ISSUE THREAD

**Issue by herbraab** [IAU-ADES/ADES-Master#4]
May I suggest to add the filter trough which an exposure was taken to the Photometry Group, as an optional field?

Currently, the filter may be listed in the Observation Context. I think it would be nice to have the filter, together with the color band of the reference star magnitudes, in the Photometry Group. In that way, all relevant information will be found in the Observation Element. That would also eliminate the need to have a new Observation Context whenever the filter is switchd.

Maybe we can consider this for the next version of ADES.

Thank you,
  Herbert Raab

**Comment by stevechesley** [comment]
Resolved with PR #47.

N.B. As indicated in the documentation, the `fltr` element indicates the filter used on the camera. It is not generally useful for processing photometry, but can be vital for distinguishing simultaneous observations reported from a multi-filter camera system. Without this information, such astrometry is likely to be interpreted as a remeasurement or duplication.

The `band` element should always reflect the passband used for the photometric reference stars, i.e., that of `photCat`, or `astCat` if `photCat` is not reported.
