### ISSUE TITLE
obsTime conversion in mpc80coltoxml

### ISSUE THREAD

**Issue by stevechesley** [IAU-ADES/ADES-Master#59]
Compared to mpc80coltoxml.py, the MPC is writing an extra digit for the seconds in obsTime when converting from obs80. 

The ADES tools should match what the MPC is doing, which can be summarized as having 3 less digits after the decimal point for obsTime seconds than were found for the decimal day. 

So `2024-04-18.215907` will go to `2024-04-18T05:10:54.365Z`, etc. But integer seconds is the lowest precision allowed in ADES. So `2024-04-18.25` will go to `2024-04-18T06:00:00Z`. 

@federicaspoto please make sure I've got this right...

**Comment by Bill-Gray** [comment]
Is that really the way we're supposed to do it?  Your example to 10^-6 days = 0.0864 seconds requires the time to be given to 0.01 second precision to ensure round-tripping (80-column to ADES back to 80-column);  the millisecond precision doesn't really harm things,  but I don't see how it helps?

I've been converting 10^-5 day punch-card times to have 0.1-second precision and 10^-6-day ones to 0.01-second precision.

**Comment by federicaspoto** [comment]
> So `2024-04-18.215907` will go to `2024-04-18T05:10:54.365Z`, etc. But integer seconds is the lowest precision allowed in ADES. So `2024-04-18.25` will go to `2024-04-18T06:00:00Z`.

@stevechesley you forgot a zero at the end, but other than that, everything is correct:
`2024-04-18.25` go to `2024-04-18T06:00:00.000Z`

**Comment by federicaspoto** [comment]
@Bill-Gray that's exactly as Steve described.

**Comment by Bill-Gray** [comment]
@stevechesley @federicaspoto - thanks for the explanation.   The extra digits don't really harm anything,  and round-trip conversion should use `precTime` anyway.  So... carry on;  I have no reasonable grounds for objection.

**Comment by stevechesley** [comment]
OK, final answer: obs80 -> ADES always round obsTime to nearest millisecond. 

@stevenstetzler go ahead with this when able.
