### ISSUE TITLE
Minor typo in pdf

### ISSUE THREAD

**Issue by schastel** [IAU-ADES/ADES-Master#6]
Hi,

There is a minor typo in the ADES pdf:
In 4.1, page 7:
`An ADES file must always include the ADES root element ades with a version attribute:
<ades version='2016'>`
should be:
`<ades version='2017'>`

Notes:

- I double-checked with what the XSD accepts (i.e. 2017)
- I've seen no other occurrence (the full example page 32 uses 2017)

**Comment by stevechesley** [comment]
Fixed.
