### ISSUE TITLE
New magnitude bands

### ISSUE THREAD

**Issue by federicaspoto** [IAU-ADES/ADES-Master#60]
@stevechesley would it be possible to add new magnitude bands for LSST to the list of allowed values. The band identifiers proposed by Mario are: `Lu, Lg, Lr, Li, Lz, Ly`
If needed, Mario also linked the following pages: 

- https://speclite.readthedocs.io/en/latest/filters.html#lsst-2023-filters, 
- https://github.com/lsst/throughputs. 
I am already adding them on the MPC side. 

Would it be also possible to add the band `VR`. It has been requested as part of a Jira ticket related to the new discoveries found by Joachim Moyens and the Asteroid Institute Team using THOR on the NOIRlab Source Catalog DR2. They also told us that they could give us the corrections to V-band if needed and we share it with CNEOS. Information on DECam VR band can be found here: https://noirlab.edu/science/programs/ctio/filters/Dark-Energy-Camera. 

Thank you,
Federica

**Comment by stevechesley** [comment]
@federicaspoto This looks like a beneficial change, but there is nothing to do on the ADES-Master side for this. ADES validation only verifies that `band` is 1-3 alphanumeric characters. Actual content is validated by MPC on submission according to the allowed values list that MPC maintains. (See discussion on page 21 of [docs](https://github.com/IAU-ADES/ADES-Master/blob/master/ADES_Description.pdf).)

**Comment by federicaspoto** [comment]
@stevechesley that's great! Sorry about this. I'll close the ticket.
