### ISSUE TITLE
packUtil.py does not have CMO

### ISSUE THREAD

**Issue by Yeqzids** [IAU-ADES/ADES-Master#9]
https://github.com/IAU-ADES/ADES-Master/blob/8c9658056cd9809b201ce5f12ba098171d303dc1/Python/bin/packUtil.py#L24 does not have CMO (CMOS) defined in https://minorplanetcenter.net/iau/info/ADESFieldValues.html.

**Comment by stevechesley** [comment]
I added 'CMO' = 'B' to the mode codeDict. This should allow conversion between mpc80col and xml for CMOS observations.

**Comment by stevechesley** [comment]
Further testing revealed a few more fixes were required to get mpc80coltoxml to work with CMOS observations. Should work both ways now.
